[package]
name = "shouxtech/observers"
description = "A collection of observer utility functions"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]